version: '3.0'

services:

  nginx:
    image: nginx
    environment:
      - VIRTUAL_HOST=site.local
    ports:
      - "90:80"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf
      - ./:/var/www/
    networks:
      - fb_network

  php:
    build:
      context: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/
    networks:
      - fb_network

#  postgres:
#    image: postgres:13.3
#    environment:
#      POSTGRES_DB: "fobosdb"
#      POSTGRES_USER: "admin"
#      POSTGRES_PASSWORD: "admin"
#    ports:
#      - "5432:5432"
#    networks:
#      - fb_network

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin1}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
    ports:
      - "5432:5432"
    networks:
      - fb_network
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

networks:
  fb_network:
    driver: bridge

#Volumes
volumes:
  mariadb:
    driver: local

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
